Add ANTLR4 syntax injection to markdown
mike-lischke/vscode-antlr4 pull request #159
Opened 2022-02-15 16:06 UTC by hazer-hazer

This pull request adds support for ANTLR4 syntax in markdown fenced code blocks.
It is implemented using injection grammars, you can read more about it [in official VSCode docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars).

2022-02-16 15:02 UTC, mike-lischke requested changes
Pretty cool, if that works like planned 😀

But pls remove the version change in package.json. This is only done on a release. Remove the change will also remove changes in package-lock.json.

2022-02-16 16:33 UTC, hazer-hazer commented
Okay, done!

2022-02-16 18:58 UTC, mike-lischke approved these changes

2022-02-16 18:59 UTC, merged

2022-02-16 19:00 UTC, mike-lischke commented
Oh, I forgot something. Please add yourself to the contributors.txt file!

2022-02-17 12:15 UTC, hazer-hazer commented
That's cute, here's a PR #163