Add a config variable to allow users to set the Java executable location (fixes issue #57)
mike-lischke/vscode-antlr4 pull request #273
Opened 2024-05-27 19:04 UTC by parkerlamb

Fixes issue #57.

This adds a new configuration variable called `javaHomeOverride`. This allows users to explicitly set JAVA_HOME if it is not present or if they wish to use a different Java installation. The Java executable is looked up at `${javaHomeOverride}/bin/java` in this case.

This also changes the default behavior to use `$JAVA_HOME/bin/java` as the Java executable to be consistent.

If neither of `javaHomeOverride` or the JAVA_HOME environment variable are set then the extension attempts to launch `java` in PATH as before.

I'm happy to adjust this as needed, feedback welcome.

2024-05-28 07:14 UTC, mike-lischke requested changes
Please add a note to the documentation.

2024-05-28 07:14 UTC, mike-lischke commented
You also have to complete the DCO check. Follow the "Details" link to learn how to do that.

2024-05-29 07:43 UTC, mike-lischke approved these changes

2024-05-29 07:43 UTC, merged

2024-05-29 07:43 UTC, mike-lischke commented
Thanks!

2024-08-21 02:38 UTC, 7c00 commented
hi @mike-lischke, could you publish a new release to include this feature?

2024-08-23 09:31 UTC, RedHotUnicorn commented
hi @mike-lischke , we really would like to get an ew release with that feature. thanks